### ISSUE TITLE
Implement new purchases API

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-convertkit#14]
ConvertKit has a purchases API now to record purchase data on accounts. 

http://developers.convertkit.com/#purchases

**Comment by nosegraze** [comment]
I've been in touch with ConvertKit and they've said the purchases endpoint isn't quite stable yet. They said they'd get back in touch with me once they've updated their docs and stabilized it.

**Comment by pippinsplugins** [comment]
@nosegraze what email are you using? I've got a conversation going with Nathan Barry on this.

**Comment by growdev** [comment]
@pippinsplugins @nosegraze We have the purchases API built into the SDK [here](https://github.com/ConvertKit/ConvertKitSDK-PHP/blob/master/src/ConvertKitAPI.php#L391) and a test [here](https://github.com/ConvertKit/ConvertKitSDK-PHP/blob/master/tests/ConvertKitAPITest.php#L243) if it helps. 

Note: There was also a small update to the purchases API earlier this week and the docs have already been updated.

**Comment by pippinsplugins** [comment]
Thanks @growdev!

**Comment by nosegraze** [comment]
PR: #15

I did my own testing on this and it worked okay, but I'd feel better if someone else tested it too. :P

**Comment by growdev** [comment]
I'll test it!

**Comment by pippinsplugins** [comment]
Merged! @nosegraze please go ahead and deploy the update!
